language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t freddocker00/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true freddocker00/react-test npm test -- --coverage

after_success:
  - docker build -t freddocker00/multi-client ./client
  - docker build -t freddocker00/multi-nginx ./nginx
  - docker build -t freddocker00/multi-server ./server
  - docker build -t freddocker00/multi-worker ./worker
  # log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push freddocker00/multi-client
  - docker push freddocker00/multi-nginx
  - docker push freddocker00/multi-server
  - docker push freddocker00/multi-worker

